# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: |
    ci(pre-commit.ci): apply auto fixes from pre-commit.com hooks

    For more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: |
    ci(pre-commit.ci): perform `pre-commit` autoupdate
  autoupdate_schedule: quarterly
  skip: []
  submodules: false
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        name: Check for Git merge conflicts
        args: [--assume-in-merge]
        exclude: ^docs/AUTHORS.rst$
  - repo: https://github.com/dafyddj/mirrors-commitlint
    rev: v19.8.1
    hooks:
      - id: commitlint
      - id: commitlint-ci
  - repo: https://github.com/rubocop-hq/rubocop
    rev: v1.78.0
    hooks:
      - id: rubocop
        name: Check Ruby files with rubocop
        args: [--debug]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Check shell scripts with shellcheck
        files: ^.*\.(sh|bash|ksh)$
        types: []
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: Check YAML syntax with yamllint
        args: [--strict]
        types: [file]
        # Files to include
        # 1. Obvious YAML files
        # 2. `pillar.example` and similar files
        # 3. SLS files under directory `test/` which are pillar files
        # Files to exclude
        # 1. SLS files under directory `test/` which are state files
        # 2. `kitchen.vagrant.yml`, which contains Embedded Ruby (ERB) template syntax
        # 3. YAML files heavily reliant on Jinja
        # 4. `.copier-answers.yml` and its variants which are auto-generated
        files: |
          (?x)^(
                .*\.yaml|
                .*\.yml|
                \.salt-lint|
                \.yamllint|
                .*\.example|
                test/.*\.sls
          )$
        exclude: |
          (?x)^(
                \.copier-answers(\..+)?\.ya?ml|
                kitchen.vagrant.yml|
                test/.*/states/.*\.sls
          )$
  - repo: https://github.com/warpnet/salt-lint
    rev: v0.9.2
    hooks:
      - id: salt-lint
        name: Check Salt files using salt-lint
        files: ^.*\.(sls|jinja|j2|tmpl|tst)$
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.5
    hooks:
      - id: rstcheck
        name: Check reST files using rstcheck
        exclude: 'docs/CHANGELOG.rst'
        additional_dependencies: [sphinx==7.2.6]
  - repo: https://github.com/saltstack-formulas/mirrors-rst-lint
    rev: v1.4.0
    hooks:
      - id: rst-lint
        name: Check reST files using rst-lint
        exclude: |
            (?x)^(
                docs/CHANGELOG.rst|
                docs/TOFS_pattern.rst|
                docs/CONTRIBUTING_DOCS.rst|
                docs/index.rst|
            )$
        additional_dependencies: [pygments==2.16.1]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.42.2
    hooks:
      - id: renovate-config-validator
        name: Check Renovate config with renovate-config-validator
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows
        name: Check GitHub workflows with check-jsonschema
        args: [--verbose]
      - id: check-gitlab-ci
        name: Check GitLab CI config with check-jsonschema
        args: [--verbose]
  - repo: https://github.com/standard/standard
    rev: v17.1.2
    hooks:
      - id: standard
        name: Check JavaScript files using standardJS
